# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='assgts',
            new_name='evals_url',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='grading',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='evals',
        ),
        migrations.RemoveField(
            model_name='course',
            name='final',
        ),
        migrations.RemoveField(
            model_name='course',
            name='midterm',
        ),
        migrations.RemoveField(
            model_name='course',
            name='otherinfo',
        ),
        migrations.RemoveField(
            model_name='course',
            name='otherreq',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='course',
            name='papers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prereqs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pset',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='takehome',
        ),
    ]
