# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 05:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_combo',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['']], size=None),
        ),
    ]
