# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 20:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_profile_course_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_combo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
    ]
