# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180414_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='course_combo',
            field=models.TextField(default=None),
        ),
    ]
