# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_combination_comb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='registrar_combo',
            field=models.TextField(default=None, null=True),
        ),
    ]
