# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_combination_registrar_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combination',
            name='course_combo',
            field=models.TextField(default=None, null=True),
        ),
    ]
