# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 16:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180416_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_courses', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('must_dept', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('distribution', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('max_dept', models.SmallIntegerField(default=-1)),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('full', models.BooleanField(default=False)),
                ('pdf', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='courses.Profile')),
            ],
        ),
    ]
