# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180421_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='enroll',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='limit',
            field=models.SmallIntegerField(default=0),
        ),
    ]
