# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20180425_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='courses.Profile'),
        ),
    ]
