# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20180426_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combination',
            name='deleted',
        ),
    ]
