# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 01:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20180428_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_fields', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='courses.Profile')),
            ],
        ),
    ]
