# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 02:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20180430_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
