# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 23:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_favorite_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='priority',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
