# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_filter_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_faves',
            field=models.TextField(default=''),
        ),
    ]
