# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_profile_previous_faves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='previous_faves',
        ),
    ]
