# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20180504_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='max_dept',
            field=models.SmallIntegerField(default=5),
        ),
    ]
